### ISSUE TITLE
New feature: Meetup signup

### ISSUE THREAD

**Issue by antoniomatheus** [antoniomatheus/Meetapp#3]
**Requirements**

- The user can signup in events that she/he is not organizing.
- The meetup should not have occurred yet.
- The user can not signup to the same meetup more than once.
- The user can not signup to meetups that take place at the same time.
- Every time a user signup in a meetup send an email to the meetup organizer with the data about the user

**Comment by antonio-matheus** [comment]
**Implementation**
- [ ] Create a route to signup for a meetup using its ID
- [ ] Create a column in the meetups table to hold all signed up users' ID, must reference the users table.
- [ ] Create a column in the users table to hold all meetups that the user is signed up, must reference the meetups table.
- [ ] Create a controller to sign up and unsubscribe the user for meetups.
